cassandra:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - frontend
            - history
            - matching
            - worker
            - zookeeper
            - kafka
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - cassandra
            - elasticsearch-master
        topologyKey: kubernetes.io/hostname

server:
  frontend:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - frontend
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cassandra
          topologyKey: kubernetes.io/hostname
 
  history:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - history
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cassandra
          topologyKey: kubernetes.io/hostname
  

  matching:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - matching
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cassandra
          topologyKey: kubernetes.io/hostname

  worker:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - worker
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cassandra
          topologyKey: kubernetes.io/hostname
