server:
  config:
    logLevel: "debug,info"

    numHistoryShards: 512

    persistence:
      default:
        driver: "cassandra"

        cassandra:
          hosts: ["cassandra.default.svc.cluster.local"]
          port: 9042
          keyspace: temporal
          user: "user"
          password: "password"
          existingSecret: ""
          consistency: One

      visibility:
        driver: "cassandra"

        cassandra:
          hosts: ["cassandra.default.svc.cluster.local"]
          port: 9042
          keyspace: temporal_visibility
          user: "user"
          password: "password"
          existingSecret: ""
          consistency: One

cassandra:
  enabled: false

mysql:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
