cassandra:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - frontend
            - zookeeper
            - kafka
          - key: app
            operator: In
            values:
            - cassandra
            - elasticsearch-master
        topologyKey: kubernetes.io/hostname

server:
  frontend:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - frontend
              - zookeeper
              - kafka
            - key: app
              operator: In
              values:
              - cassandra
              - elasticsearch-master
          topologyKey: kubernetes.io/hostname
 
  history:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - history
              - zookeeper
              - kafka
            - key: app
              operator: In
              values:
              - cassandra
              - elasticsearch-master
          topologyKey: kubernetes.io/hostname
  

  matching:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - matching
              - zookeeper
              - kafka
            - key: app
              operator: In
              values:
              - cassandra
              - elasticsearch-master
          topologyKey: kubernetes.io/hostname

  worker:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - worker
              - zookeeper
              - kafka
            - key: app
              operator: In
              values:
              - cassandra
              - elasticsearch-master
          topologyKey: kubernetes.io/hostname
