apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "temporal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  config_template.yaml: |-
    log:
      stdout: true
      level: {{ .Values.server.config.logLevel | quote }}

    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: {{ .Values.server.config.numHistoryShards }}
      datastores:
        default:
          {{- if eq (include "temporal.persistence.driver" (list . "default")) "cassandra" }}
          cassandra:
            hosts: {{ include "temporal.persistence.cassandra.hosts" (list . "default") }}
            port: {{ include "temporal.persistence.cassandra.port" (list . "default") }}
            password: {{ `{{ .Env.TEMPORAL_STORE_PASSWORD }}` }}
            {{- with (omit .Values.server.config.persistence.default.cassandra "hosts" "port" "password" "existingSecret") }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        visibility:
          {{- if eq (include "temporal.persistence.driver" (list . "visibility")) "cassandra" }}
          cassandra:
            hosts: {{ include "temporal.persistence.cassandra.hosts" (list . "visibility") }}
            port: {{ include "temporal.persistence.cassandra.port" (list . "visibility") }}
            password: {{ `{{ .Env.TEMPORAL_VISIBILITY_STORE_PASSWORD }}` }}
            {{- with (omit .Values.server.config.persistence.visibility.cassandra "hosts" "port" "password" "existingSecret") }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

    server:
      ringpop:
        name: temporal
        maxJoinDuration: 30s
        broadcastAddress: {{ `{{ default .Env.POD_IP "0.0.0.0" }}` }}

      pprof:
        port: 7936


    services:
      frontend:
        rpc:
          grpcPort: {{ include "temporal.frontend.grpcPort" . }}
          membershipPort: {{ include "temporal.frontend.membershipPort" . }}
          bindOnIP: "0.0.0.0"
        metrics:
          tags:
            type: frontend
          prometheus:
            timerType: {{ default .Values.server.metrics.prometheus.timerType .Values.server.frontend.metrics.prometheus.timerType }}
            listenAddress: "0.0.0.0:9090"

      history:
        rpc:
          grpcPort: {{ include "temporal.history.grpcPort" . }}
          membershipPort: {{ include "temporal.history.membershipPort" . }}
          bindOnIP: "0.0.0.0"
        metrics:
          tags:
            type: history
          prometheus:
            timerType: {{ default .Values.server.metrics.prometheus.timerType .Values.server.history.metrics.prometheus.timerType }}
            listenAddress: "0.0.0.0:9090"

      matching:
        rpc:
          grpcPort: {{ include "temporal.matching.grpcPort" . }}
          membershipPort: {{ include "temporal.matching.membershipPort" . }}
          bindOnIP: "0.0.0.0"
        metrics:
          tags:
            type: matching
          prometheus:
            timerType: {{ default .Values.server.metrics.prometheus.timerType .Values.server.matching.metrics.prometheus.timerType }}
            listenAddress: "0.0.0.0:9090"

      worker:
        rpc:
          grpcPort: {{ include "temporal.worker.grpcPort" . }}
          membershipPort: {{ include "temporal.worker.membershipPort" . }}
          bindOnIP: "0.0.0.0"
        metrics:
          tags:
            type: worker
          prometheus:
            timerType: {{ default .Values.server.metrics.prometheus.timerType .Values.server.worker.metrics.prometheus.timerType }}
            listenAddress: "0.0.0.0:9090"

    clusterMetadata:
      enableGlobalDomain: false
      failoverVersionIncrement: 10
      masterClusterName: "active"
      currentClusterName: "active"
      clusterInformation:
        active:
          enabled: true
          initialFailoverVersion: 0
          rpcName: "temporal-frontend"
          rpcAddress: "127.0.0.1:7933"

    dcRedirectionPolicy:
      policy: "noop"
      toDC: ""

    archival:
      status: "disabled"

    publicClient:
      hostPort: "{{ include "temporal.componentname" (list . "frontend") }}:{{ .Values.server.frontend.service.port }}"
