name: Release Charts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Temporal version to use for release (for example 1.22.4)"
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Empty
        run: |
          echo Doing nothing
